### PR TITLE
Fix `UiaEnum` comparison operators for all types `UiaEnum` can be constructed out of

### LINKED ISSUE #38: `UiaEnum` cannot be compared against anything but WinRT enum values
The below code does not compile due to multiple operators matching right-hand side values:
```
auto operationScope = UiaOperationScope::StartNew();

// Give this operation a remote context.
UiaElement displayElement{ focusedElement };
operationScope.BindInput(displayElement);

// Ask for the control type of the imported element (which is represented as a `UiaEnum`).
auto controlType = displayElement.GetControlType(false /* useCachedApi */);

// Compare against different control type representations.
auto equalToAbstractionValue = (controlType == controlType); // Does not compile [1]
auto equalToComEnum = (controlType == UIA_TextControlTypeId); // Does not compile [2]
auto equalToWinRtEnum = (controlType == winrt::Microsoft::UI::UIAutomation::AutomationControlType::Text);

auto notEqualToAbstractionValue = (controlType != controlType); // Does not compile [1]
auto notEqualToComEnum = (controlType != UIA_TextControlTypeId); // Does not compile [2]
auto notEqualToWinRtEnum = (controlType != winrt::Microsoft::UI::UIAutomation::AutomationControlType::Text);

// Return the result.
operationScope.BindResult(equalToAbstractionValue, equalToComEnum, equalToWinRtEnum, notEqualToAbstractionValue, notEqualToComEnum, notEqualToWinRtEnum);
operationScope.Resolve();

// Ensure the correct results have been returned.
Assert::IsTrue(static_cast<bool>(equalToAbstractionValue));
Assert::IsTrue(static_cast<bool>(equalToComEnum));
Assert::IsTrue(static_cast<bool>(equalToWinRtEnum));
Assert::IsFalse(static_cast<bool>(notEqualToAbstractionValue));
Assert::IsFalse(static_cast<bool>(notEqualToComEnum));
Assert::IsFalse(static_cast<bool>(notEqualToWinRtEnum));
```
Looks like this is a conflict between conversion operators (to local and remote types) and comparison operators (defined for the types).

It sounds like we could reduce our comparison operators to 2 types:
1. `UiaEnum`,
2. T (for both COM and WinRT enum, since the compiler sees possible conversions from COM values [which are raw numbers] to WinRT enum values).

Plus, we could remove the comparisons against rvalue COM enums (that is already covered by other operators as far as I can tell).

### PR DESCRIPTION
**Pull request by LukaszMakar**
`UiaEnum` is a wrapper type that can be constructed out of the following types:
1. COM `enum`s such as `CONTROLTYPEID` (local type),
2. WinRT `enum`s of the operation builder such as `AutomationControlType` (local type),
3. Corresponding stand-in (numeric) type (remote type),
4. `UiaEnum` itself (copy-construction).

The abstraction class is providing 3 different types of comparison methods against the mentioned values depending on what the caller has. In short, `UiaEnum` allows comparing against COM, WinRT `enum`s as well as the `UiaEnum` type (the abstraction tries to hide the corresponding stand-in type).

However, this does not work today due to ambiguity of defined comparison operators (and which should be applied for which situation/type).

In fact, the only comparison operators that work are the ones for numeric values (such as `CONTROLTYPEID` cast to `long` in case of `UiaControlType`) and WinRT `enum`s (such as the `AutomationControlType` `enum class`). But these comparators cannot be applied when the code author tries to write UIA operation abstraction-based functions that take UIA abstraction types as the functions usually cannot assume whether abstraction types hold "local" or "remote" types (and therefore casting `UiaEnum`s is not an option).

This change attempts to fix that problem by:
1. Keeping the comparison operators for comparing `UiaEnum`s,
2. Reduces other operators to template-based functions that take a value to compare a `UiaEnum` against, create a `UiaEnum` out of the value and then compares the two (using the kept operators).
3. Removing any other defined comparison operators for the COM and WinRT `enum` types as well as the `rvalue` comparison types.

With the change, ensuring type correctness is pushed towards `UiaEnum` constructors since the operators create `UiaEnum` instances out of `rhs` before comparing values.

Fixes #38

### CODE REVIEW

File: src/UIAutomation/UiaOperationAbstraction/UiaOperationAbstraction.h [hunk 1]
```diff
@@ -973,7 +937,7 @@ namespace UiaOperationAbstraction
                 return std::get<StandinT>(mutableThis.m_member).IsEqual(std::get<StandinT>(mutableRhs.m_member));
             }
 
-            return std::get<ComEnumT>(m_member) == rhs;
+            return std::get<ComEnumT>(m_member) == static_cast<ComEnumT>(rhs);
```
Comment (zhayuli) [inline src/UIAutomation/UiaOperationAbstraction/UiaOperationAbstraction.h:940]: >static_cast<ComEnumT>(rhs) [](start = 51, length = 26)

Feels like this is what we usually do??
`std::get<ComEnumT>(rhs.m_member)`

**Review by zhayuli — APPROVED** [review]
:shipit:

File: src/UIAutomation/UiaOperationAbstraction/UiaOperationAbstraction.h (hunk 1 above)
Comment (LukaszMakar) [reply src/UIAutomation/UiaOperationAbstraction/UiaOperationAbstraction.h:940]: That's what the conversion operator is. :) But I am OK with adjusting it.

File: src/UIAutomation/FunctionalTests/UiaOperationAbstractionTests.cpp [hunk 2]
```diff
@@ -804,5 +804,62 @@ namespace UiaOperationAbstractionTests
         {
             ConvertRectTest(true /* useRemoteOperations */);
         }
+
+        void CompareEnumTest(bool useRemoteOperations)
```
Comment (mlalic) [inline src/UIAutomation/FunctionalTests/UiaOperationAbstractionTests.cpp:808]: >CompareEnumTest [](start = 13, length = 15)

Test

**Review by mlalic — APPROVED** [review]
:shipit:

File: src/UIAutomation/FunctionalTests/UiaOperationAbstractionTests.cpp [hunk 3]
```diff
@@ -857,5 +857,62 @@ namespace UiaOperationAbstractionTests
...
+            ModernApp app(L"Microsoft.WindowsCalculator_8wekyb3d8bbwe!App");
+            app.Activate();
+
+            // Set focus to the display element.
+            auto focusedElement = WaitForElementFocus(L"Display is 0");
+
+            // Initialize the UIA Remote Operation abstraction.
+            const auto cleanup = InitializeUiaOperationAbstraction(useRemoteOperations);
+
+            // Create rectangles using 2 different input types and check that they are the same when returned
```
Comment (LukaszMakar) [inline src/UIAutomation/FunctionalTests/UiaOperationAbstractionTests.cpp:873]: Which I changed this comment, though. #TooMuchCopyPaste
