### PR TITLE
scope::resolve throws more meaningful exceptions for statuses such as instructionLimitExceeded

### LINKED ISSUE #87: Produce a more meaningful error code on `AutomationRemoteOperationStatus::InstructionLimitExceeded`
UIA returns `AutomationRemoteOperationStatus::InstructionLimitExceeded` when the number of instructions executed in the remote process exceeds 10000. However, currently the wrapper just transforms this into `E_FAIL` in `AutomationRemoteOperationResultSet::OperationStatus`. In `UiaOperationScope::Resolve`, this `E_FAIL` is plumbed through to the client.

We should provide a way to determine whether the remote operation exited with `InstructionLimitExceeded`. I'm listing three potential ways here, although more are certainly possible:

- Create a custom HRESULT using the [customer bit](https://docs.microsoft.com/en-us/openspecs/windows_protocols/ms-erref/0642cb2f-2075-4469-918c-4441e69c548a) and return this instead of `E_FAIL`.
- Create a custom exception which `UiaOperationScope::Resolve` throws on `InstructionLimitExceeded`.
- Add support to `AutomationRemoteOperationResultSet` to return whether `InstructionLimitExceeded` occurred, and provide an alternative to `UiaOperationScope::Resolve` which returns an `AutomationRemoteOperationResultSet`.

### PR DESCRIPTION
**Pull request by michaelDCurran**
Fixes #87

The following new exceptions are thrown by UiaOperationScope::Resolve due to their respective operation result status values:
* ExecutionFailureException
* MalformedBytecodeException
* UnhandledRemoteException
* InstructionLimitExceededException

These new exceptions all inherit from winrt::hresult_error, so existing code that is catching winrt::result_error will still function exactly the same way.

Further to this, if InstructionLimitExceededException is thrown, any result variables already calculated before the limit was hit will be still resolved, making them available locally. 

These changes make it technically possible now to write remoted algorithms with the abstraction library, such that they could be continued on in a second remote call, if the first failed with an InstructionLimitExceeded exception, as result variables could be used to keep track of the state of the algorithm.
Also, all changes have been made to be fully compatible with previous code.

In order to make all this work, several other changes needed to be made.

The low-level winrt API's AutomationRemoteOperationResultSet::OperationStatus method was problematic as it essentially just returned the ExtendedError value, but tweaked for certain status values. E.g. E_FAIL was returned for InstructionLimitExceeded. This then meant that higher-level APIs could never access the actual OperationStatus value.
Therefore, the AutomationRemoteOperationResultSet class has the following changes:
* Added a Status method, which returns the raw AutomationRemoteOperationStatus value of the result. E.g. success, MalformedBytecodeInstruction, UnhandledException, ExecutionFailure. 
* Added an ExtendedError method, which returns the ExtendedError HRESULT value.
* Added a comment to the OperationStatus method noting it should be deprecated in favor of the separate Status and ExtendedError methods.
 
The high-level abstraction library's UiaOperationScope::ResultInternal now fetches Status and ExtendedError separately, rather than calling the old OperationStatus method. It then gives both of these values back by reference.
However, to ensure compatibility for higher-level APIs, extendedError is forced to E_FAIL if the status is InstructionLimitExceeded. Note that not doing this, ExtendedError would be S_OK. 

ResultInternal also now resolves all available result variables when the status is InstructionLimitExceeded, not just when the status is Success.

The high-level abstraction library's UiaOperationScope::ResolveHr method now returns the ExtendedError from ResolveInternal. But from the caller's point of view, there is no change at all.
 
The high-level abstraction library's UiaOperationScope::Resolve method now calls ResolveInternal directly, rather than ResolveHr. This is so it gets access to both the raw status and ExtendedError.
Based on the Status, Resolve throws the appropriate Exception, instantiated with the ExtendedError as its HRESULT error code.

Finally, tests have been added:
* executionFailureException: Testing that this exception is thrown by trying to execute a remote operation interacting with elements from more than one process. 
* UnhandledRemoteException: Testing that this exception is thrown by trying to fetch the first element from an empty UiaArray.
* InstructionLimitExceededException: Testing that this exception is thrown by constantly incrementing a UiaInt until the instruction limit is hit. 

I was not able to come up with any way of testing MalformedBytecodeException - the winrt and abstraction APIs should never allow a caller to produce this situation anyway I think.

### CODE REVIEW

File: src/UIAutomation/UiaOperationAbstraction/UiaOperationAbstraction.cpp [hunk 1]
```diff
@@ -2316,22 +2316,37 @@ namespace UiaOperationAbstraction
...
-        HRESULT operationResult = S_OK;
-        ResolveHrInternal(operationResult);
-        THROW_IF_FAILED(operationResult);
+        auto status = winrt::Windows::UI::UIAutomation::Core::AutomationRemoteOperationStatus::Success;
+        HRESULT extendedError = S_OK;
+        ResolveInternal(status, extendedError);
+        switch(status)
+        {
+            case winrt::Windows::UI::UIAutomation::Core::AutomationRemoteOperationStatus::MalformedBytecode:
+            throw MalformedBytecodeException(extendedError);
```
Comment (beweedon) [inline src/UIAutomation/UiaOperationAbstraction/UiaOperationAbstraction.cpp:2325]: **nit:** Could we indent the `case` bodies one more?

File: src/UIAutomation/UiaOperationAbstraction/UiaOperationAbstraction.cpp [hunk 2]
```diff
@@ -2316,22 +2316,37 @@ namespace UiaOperationAbstraction
...
-        return operationResult;
+        auto status = winrt::Windows::UI::UIAutomation::Core::AutomationRemoteOperationStatus::Success;
+        HRESULT extendedError = S_OK;
+        ResolveInternal(status, extendedError);
+        return extendedError;
     }
     CATCH_RETURN();
   
-    void UiaOperationScope::ResolveHrInternal(HRESULT& operationResult)
+    void UiaOperationScope::ResolveInternal(winrt::Windows::UI::UIAutomation::Core::AutomationRemoteOperationStatus& status, HRESULT& extendedError)
```
Comment (beweedon) [inline src/UIAutomation/UiaOperationAbstraction/UiaOperationAbstraction.cpp:2346]: While we're here could we change this to return an `std::pair<AutomationRemoteOperationState, HRESULT>` instead of using out params?

File: src/UIAutomation/FunctionalTests/UiaOperationAbstractionTests.cpp [hunk 3]
```diff
@@ -2715,5 +2715,113 @@ namespace UiaOperationAbstractionTests
         {
             UiaGuidLookupAnnotationTypeIdTest(false);
         }
+
+        // Test that hitting the instruction limit in a remote operation causes an InstructionLimitExceededException in resolve.
+        TEST_METHOD(instructionLimitExceeded)
```
Comment (beweedon) [inline src/UIAutomation/FunctionalTests/UiaOperationAbstractionTests.cpp:2720]: **nit:** Capitalize test names

File: src/UIAutomation/FunctionalTests/UiaOperationAbstractionTests.cpp [hunk 4]
```diff
@@ -2715,5 +2715,113 @@ namespace UiaOperationAbstractionTests
...
+                {
+                    scope.Resolve();
+                }
+                catch(winrt::hresult_error& e)
+                {
+                    Assert::AreEqual(E_UNEXPECTED, static_cast<HRESULT>(e.code()));
+                    throw;
+                }
+            });
+        }
```
Comment (beweedon) [inline src/UIAutomation/FunctionalTests/UiaOperationAbstractionTests.cpp:2825]: We can produce malformed bytecode errors by passing over 1MB of bytecode to the remote process. Could we add a test for that? It should be possible to do that similarly to the instruction limit test, but with an actual C++ loop:

```cpp
for (int i = 0; i < 1048576; ++i)
{
    UiaBool b = true;
}
```

We definitely don't need to iterate this many times (the `NewBool` instruction plus its operands is a total of 9 bytes), but this is the basic idea.

**Comment by beweedon** [comment]
This looks great! I don't have any major feedback, just what I've commented. Thanks for looking into this!

**Comment by michaelDCurran** [comment]
@beweedon  I believe I have addressed all your comments. I settled on 200000 for the for loop. As 100000 is not enough and still throws InstructionLimitExceeded rather than MalformedBytecodeException.

File: src/UIAutomation/UiaOperationAbstraction/UiaOperationAbstraction.cpp [hunk 5]
```diff
@@ -2316,22 +2316,33 @@ namespace UiaOperationAbstraction
 
     void UiaOperationScope::Resolve()
     {
-        HRESULT operationResult = S_OK;
-        ResolveHrInternal(operationResult);
-        THROW_IF_FAILED(operationResult);
+                auto [status, extendedError] = ResolveInternal();
```
Comment (csauls) [inline src/UIAutomation/UiaOperationAbstraction/UiaOperationAbstraction.cpp:2319]: nit: This looks extra indented in my view.

File: src/UIAutomation/UiaOperationAbstraction/UiaOperationAbstraction.cpp [hunk 6]
```diff
@@ -2346,9 +2357,25 @@ namespace UiaOperationAbstraction
...
+                // and resolve will throw InstructionLimitExceededException (which inherits from winrt::hresult_error) with a code of E_FAIL.
+                if(status == winrt::Windows::UI::UIAutomation::Core::AutomationRemoteOperationStatus::InstructionLimitExceeded)
+                {
+                    extendedError = E_FAIL;
+                }
 
-                if (SUCCEEDED(operationResult))
+                // Fetch bound results on success, but also
+                // instruction limit exceeded, 
+                // As we no certainly some of the remote operation did execute.
```
Comment (csauls) [inline src/UIAutomation/UiaOperationAbstraction/UiaOperationAbstraction.cpp:2374]: nit: "no" -> "know"

**Comment by csauls** [comment]
When the instruction limit is hit and partial results are returned, is there any risk that some of the bound results will be in an undefined state? Can the caller always inspect the values and determine if they are meaningful?

I understand from the description that it is up to the author to devise the method for resuming the operation, such as returning data that indicates how far the execution got before it was halted. Am I understanding correctly?

**Comment by michaelDCurran** [comment]
@csauls  I am under the assumption that all Uia types are initialized to a safe value. Thus resolving them at any point in the algorithm should be safe. In deed the low-level vm allows fetching these results via the resultSet for instructionLimitExceeded, but not UnhandledException for example it seems. Which suggests that there was a decision internally to allow fetching of partial results for instructionLimitExceeded, but not other errors.
I have no further knowledge here.
But yes, you are right that it will be up to the author to write their algorithm in such a way that allows resuming.
For example, if walking a very large text range (say a large MS Word document) to collect all headings, the author would keep shrinking the given textRange as they walk, so that restarting the algorithm, they will start from where they left off.
Of course this means that the textRange variable will have to be both bound as input and also bound for resolving.

**Comment by csauls** [comment]
> @csauls I am under the assumption that all Uia types are initialized to a safe value. Thus resolving them at any point in the algorithm should be safe. In deed the low-level vm allows fetching these results via the resultSet for instructionLimitExceeded, but not UnhandledException for example it seems. Which suggests that there was a decision internally to allow fetching of partial results for instructionLimitExceeded, but not other errors. I have no further knowledge here. But yes, you are right that it will be up to the author to write their algorithm in such a way that allows resuming. For example, if walking a very large text range (say a large MS Word document) to collect all headings, the author would keep shrinking the given textRange as they walk, so that restarting the algorithm, they will start from where they left off. Of course this means that the textRange variable will have to be both bound as input and also bound for resolving.

Thanks for the additional details! I figured the objects would be in a safe state, I just didn't know if they'd be in a state to know if they had a meaningful value. A pointer may initialize to null, but there may not be a way to know if that's a result of the algorithm as well. Just something to think on if we need to have a way to make such distinctions in the future.

**Review by csauls — APPROVED** [review]

**Comment by beweedon** [comment]
I did some more digging. You should actually be able to recover any output on any error, not just `InstructionLimitExceeded`, if you're using the low level bytecode API or `Microsoft.UI.UIAutomation`. It's just `UiaOperationAbstraction` that enforces not providing returned values on error.

This doesn't necessarily apply to this PR, but it's something to keep it mind I guess.

**Review by beweedon — APPROVED** [review]
Looks great to me! I'll merge this and the other one next week to give a bit more time for review!

**Comment by michaelDCurran** [comment]
I'm having trouble writing the MalformedBytecodeException test as it 
seems an unknown c++ exception is thrown from somewhere in either 
Serialize or AutomationRemoteOperation::execute, and I don't know what 
it is.
I will keep searching.
